import { launch } from "./cdp.mjs";
const p = await launch({ width: 390, height: 844 });
const click = (label) => p.eval(`(() => { const b=[...document.querySelectorAll('button,a')].find(x=>x.textContent.includes(${JSON.stringify(label)})); if(!b) throw new Error('no '+${JSON.stringify(label)}); b.click(); })()`);
const type = (sel, v) => p.eval(`(() => { const el=document.querySelector(${JSON.stringify(sel)}); const proto = el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(proto,'value').set.call(el, ${JSON.stringify(v)}); el.dispatchEvent(new Event('input',{bubbles:true})); })()`);
await p.goto("http://localhost:3000/garde", 3000);
await p.eval("localStorage.clear()");
await p.goto("http://localhost:3000/garde", 4000);
await p.shot("w0-kind.png");
await click("Rapport de stage");
await p.sleep(800);
await p.eval(`(() => { const s=document.querySelector('select'); Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(s,'uy2-esstic'); s.dispatchEvent(new Event('change',{bubbles:true})); })()`);
await type("textarea", "Gestion électronique des archives dans une microfinance : cas d'ADVANS Cameroun");
await type('input[placeholder="NOM Prénom"]', "NGNICHANG TANDI Honorine");
await type('input[placeholder="20V3543"]', "18C0041");
await p.sleep(600);
await p.shot("w1-essentials.png");
await click("Continuer");
await p.sleep(600);
await p.shot("w2-details.png");
await click("Voir les styles");
await p.sleep(1200);
await p.shot("w3-style.png");
p.close();
